services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
      args:
        INSTANCE: private
    environment:
      JWT_SECRET: 'temp-jwt-secret-key'
      ENCRYPTION_KEY: 'temp-encryption-key-32-chars-long'

      # To enable private instance authentication, uncomment the following variables
      # SYNCIO_PRIVATE_USERNAME: ''
      # SYNCIO_PRIVATE_PASSWORD: ''
    user: "1001:1001"
    volumes:
      - syncio_data:/app/data
    ports:
      - "4000:4000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
      args:
        INSTANCE: private
    environment:
      BACKEND_URL: 'http://backend:4000'
    depends_on:
      - backend
    user: "1001:1001"
    ports:
      - "3000:3000"

volumes:
  syncio_data:
